### ISSUE TITLE
Rubric advice cannot be saved

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#185]
When attempting to save rubric advice for the "CSC/ECE 506 wiki supplement 2011" rubric, the following error occurs:

NoMethodError in Questionnaire#list

Showing app/views/questionnaire/list.html.erb where line #4 raised:

undefined method `inject' for nil:NilClass

Extracted source (around line #4):

1: <h1>Questionnaires</h1>
2: 
3: <% form_tag :action => 'list' do %>
4: 	<%= select(:display_option, :name, 
5: 			   @display_options, {}, 
6: 			   {:onchange => "document.forms[0].submit()"} ) %>
7: <% end %>

RAILS_ROOT: /local/rails/expertiza/releases/20120127015342
Application Trace | Framework Trace | Full Trace

/local/rails/expertiza/shared/bundle/ruby/1.8/gems/actionpack-2.3.14/lib/action_view/helpers/form_options_helper.rb:292:in `options_for_select'
/local/rails/expertiza/shared/bundle/ruby/1.8/gems/actionpack-2.3.14/lib/action_view/helpers/form_options_helper.rb:533:in `to_select_tag'

**Comment by efg** [comment]
This was fixed some time ago.
