### ISSUE TITLE
Error on creating assignment teams

### ISSUE THREAD

**Issue by yangsong8** [expertiza/expertiza#475]
This is spotted in Rails 4 branch. In a team assignment, when a user (not holding any topic) create a team, a error message is show:

ActiveRecord::RecordNotFound in StudentTeamsController#create
Couldn't find AssignmentTeam without an ID
app/controllers/student_teams_controller.rb:5:in `team'
app/controllers/student_teams_controller.rb:180:in `team_created_successfully'
app/controllers/student_teams_controller.rb:57:in `create'

But if I "go back one page", I found that the team was created from UI. However, another user join the team, (s)he cannot see the hyperlinks created by the team creator.

**Comment by yangsong8** [comment]
Further test: if one user select a topic first without creating a team (after getting the topic, one team will be created automatically), there is no this issue.

**Comment by yangsong8** [comment]
Fixed. It was caused by code related to "Undo" feature.
